Update Helloworld.yml

diff --git a/.github/workflows/Helloworld.yml b/.github/workflows/Helloworld.yml
--- a/.github/workflows/Helloworld.yml
+++ b/.github/workflows/Helloworld.yml
@@ -42,17 +42,17 @@ jobs:
      #   if: success() || failure() # always run even if the previous step fails
      #   run: dir /b D:\a\BratlienHelloWorld\BratlienHelloWorld\target\surefire-reports\*.txt > print.txt && For /f "delims=" %%a in ('Type "print.txt"') do (echo %%a) 
      #   shell: cmd
-      - name: Convert xml to json
-        if: success() || failure() # always run even if the previous step fails
-        id: xml2json
-        uses: fabasoad/data-format-converter-action@v0.1.7
-        with:
-         input: D:\a\BratlienHelloWorld\BratlienHelloWorld\target\surefire-reports\TEST-sample.junit.CalculateTest.xml
-         from: 'xml'
-         to: 'json'
-      - name: Print xml2json result
-        if: success() || failure() # always run even if the previous step fails
-        run: echo "${{ steps.xml2json.outputs.data }}"  
+    # - name: Convert xml to json
+    #    if: success() || failure() # always run even if the previous step fails
+    #    id: xml2json
+    #    uses: fabasoad/data-format-converter-action@v0.1.7
+    #    with:
+    #     input: D:\a\BratlienHelloWorld\BratlienHelloWorld\target\surefire-reports\TEST-sample.junit.CalculateTest.xml
+    #     from: 'xml'
+    #     to: 'json'
+    #  - name: Print xml2json result
+    #    if: success() || failure() # always run even if the previous step fails
+    #    run: echo "${{ steps.xml2json.outputs.data }}"  
     #  - name: Read test results
     #    id: testResultsFile
     #    if: success() || failure() # always run even if the previous step fails
@@ -62,12 +62,20 @@ jobs:
     #  - name: Echo migrations
     #    if: success() || failure() # always run even if the previous step fails
     #    run: echo "${{ steps.testResultsFile.outputs.content }}"
+      - name: Read XML file
+        if: success() || failure() # always run even if the previous step fails
+        id: read_file
+        uses: andstor/file-reader-action@v1
+        with: 
+          path: D:\a\BratlienHelloWorld\BratlienHelloWorld\target\surefire-reports\sample.junit.CalculateTest.txt
+      - name: File contents
+        run: echo "${ steps.read_file.outputs.contents }"
       - name: Parser results
         if: success() || failure() # always run even if the previous step fails
         uses: muinmomin/webhook-action@v1.0.0
         with:
           url: "https://pulse-7-container.qtestnet.com/webhook/53b32c57-368c-4b9b-a4e0-af11389c5438"
-          data: '{"projectId": "106715" ,"testcycle": "6334424","result":"${{ steps.xml2json.outputs.output }}"}'         
+          data: '{"projectId": "106715" ,"testcycle": "6334424","result":"${{ steps.read_file.outputs.contents}}"}'         
          # data: "${{ steps.xml2json.outputs.output }}"
          
       - name: invoke chatops pulse with json
