Update Helloworld.yml

diff --git a/.github/workflows/Helloworld.yml b/.github/workflows/Helloworld.yml
--- a/.github/workflows/Helloworld.yml
+++ b/.github/workflows/Helloworld.yml
@@ -32,10 +32,14 @@ jobs:
       #  with:
       #    #report_paths: '**/build/test-results/test/TEST-*.xml'     
       #    report_paths: 'D:\a\BratlienHelloWorld\BratlienHelloWorld\target\surefire-reports\*.xml'     
-      - name: Get All Test xml
-        if: success() || failure() # always run even if the previous step fails
-        uses: the-coding-turtle/ga-file-list@v0.4.1        
-        with:
-          directory: 'D:\a\BratlienHelloWorld\BratlienHelloWorld\target\surefire-reports'
-          file_extension: "xml"
-      
+     # - name: Get All Test xml
+     #   if: success() || failure() # always run even if the previous step fails
+     #   uses: the-coding-turtle/ga-file-list@v0.4.1        
+     #   with:
+     #     directory: 'D:\a\BratlienHelloWorld\BratlienHelloWorld\target\surefire-reports'
+     #     file_extension: "xml"
+      - name: Windows bash
+        shell: bash
+        run: | 
+          value='dir /s /b /o:gn'
+          echo The result is $value
