Update Helloworld.yml

diff --git a/.github/workflows/Helloworld.yml b/.github/workflows/Helloworld.yml
--- a/.github/workflows/Helloworld.yml
+++ b/.github/workflows/Helloworld.yml
@@ -38,10 +38,10 @@ jobs:
      #   with:
      #     directory: 'D:\a\BratlienHelloWorld\BratlienHelloWorld\target\surefire-reports'
      #     file_extension: "xml"
-     # - name: Windows change
-     #   if: success() || failure() # always run even if the previous step fails
-     #   run: dir /b D:\a\BratlienHelloWorld\BratlienHelloWorld\target\surefire-reports\*.txt > print.txt && For /f "delims=" %%a in ('Type "print.txt"') do (echo %%a) 
-     #   shell: cmd
+      - name: Windows change
+        if: success() || failure() # always run even if the previous step fails
+        run: dir /b D:\a\BratlienHelloWorld\BratlienHelloWorld\target\surefire-reports\*.xml > print.txt && For /f "delims=" %%a in ('Type "print.txt"') do (echo %%a) 
+        shell: cmd
     # - name: Convert xml to json
     #    if: success() || failure() # always run even if the previous step fails
     #    id: xml2json
@@ -65,9 +65,9 @@ jobs:
       - name: Read XML file
         if: success() || failure() # always run even if the previous step fails
         id: read_file
-        uses: andstor/file-reader-action@v1
+        uses: andstor/file-reader-action@v1.0.0
         with: 
-          path: D:\a\BratlienHelloWorld\BratlienHelloWorld\target\surefire-reports\sample.junit.CalculateTest.txt
+          path: D:\a\BratlienHelloWorld\BratlienHelloWorld\target\surefire-reports\sample.junit.CalculateTest.mxl
       - name: File contents
         run: echo "${ steps.read_file.outputs.contents }"
       - name: Parser results
