Update Helloworld.yml

diff --git a/.github/workflows/Helloworld.yml b/.github/workflows/Helloworld.yml
--- a/.github/workflows/Helloworld.yml
+++ b/.github/workflows/Helloworld.yml
@@ -40,9 +40,10 @@ jobs:
      #     file_extension: "xml"
       - name: Windows change
         if: success() || failure() # always run even if the previous step fails
-        run: dir /b D:\a\BratlienHelloWorld\BratlienHelloWorld\target\surefire-reports\*.txt > print.txt && For /f "delims=" %%a in ('Type "print.txt"') do (echo %%a) 
+        run: dir /b D:\a\BratlienHelloWorld\BratlienHelloWorld\target\surefire-reports\*.xml > print.txt && For /f "delims=" %%a in ('Type "print.txt"') do (echo %%a) 
         shell: cmd
       - name: Convert xml to json
+        if: success() || failure() # always run even if the previous step fails
         id: xml2json
         uses: fabasoad/yaml-json-xml-converter-action@main
         with:
@@ -50,13 +51,14 @@ jobs:
          from: 'xml'
          to: 'json'
       - name: Print xml2json result
+        if: success() || failure() # always run even if the previous step fails
         run: echo "${{ steps.xml2json.outputs.data }}"  
       - name: Read test results
         id: testResultsFile
         if: success() || failure() # always run even if the previous step fails
         uses: juliangruber/read-file-action@v1.1.6   
         with:
-         path: D:\a\BratlienHelloWorld\BratlienHelloWorld\target\surefire-reports\sample.junit.CalculateTest.txt
+         path: D:\a\BratlienHelloWorld\BratlienHelloWorld\target\surefire-reports\TEST-sample.junit.CalculateTest.xml
       - name: Echo migrations
         if: success() || failure() # always run even if the previous step fails
         run: echo "${{ steps.testResultsFile.outputs.content }}"
