Update HWU.yml

diff --git a/.github/workflows/HWU.yml b/.github/workflows/HWU.yml
--- a/.github/workflows/HWU.yml
+++ b/.github/workflows/HWU.yml
@@ -19,12 +19,14 @@ jobs:
         if: success() || failure()
         uses: scacap/action-surefire-report@v1
       - name: Fetch action
+        if: success() || failure() # always run even if the previous step fails
         id: pl
         uses: Rishabh510/Path-lister-action@master
         with:
           path: ".target/surefire-reports/"
           type: ".xml"
       - name: Output results
+        if: success() || failure() # always run even if the previous step fails
         run: |
           echo "Found ${{ steps.pl.outputs.path_count }} file(s) with this extension:"
           for i in ${{ steps.pl.outputs.paths }}; do
