Update HWU.yml

diff --git a/.github/workflows/HWU.yml b/.github/workflows/HWU.yml
--- a/.github/workflows/HWU.yml
+++ b/.github/workflows/HWU.yml
@@ -119,18 +119,19 @@ jobs:
         if: success() || failure() # always run even if the previous step fails
         #curl --request POST https://pulse-7-container.qtestnet.com/webhook/53b32c57-368c-4b9b-a4e0-af11389c5438 -d "projectId=106715&testcycle=6335148&result=$env.encod_data"
         run: |
-           echo ${{ env.encod_data }} 
            curlComandbase="--request POST https://pulse-7-container.qtestnet.com/webhook/53b32c57-368c-4b9b-a4e0-af11389c5438 -d"
            echo "${curlComandbase}"
-           curlComandbase="${curlComandbase} projectId=106715&testcycle=6335148&result=${{ env.encod_data }}"
+           curlComandbase="${curlComandbase} projectId=106715&testcycle=6335148&result="
+           echo "${curlComandbase}"
+           curlComandbase="${curlComandbase} ${ env.encod_data }"
            echo "${curlComandbase}"
            curl ${curlComandbase}
            
-      - name: invoke chatops pulse with json
-        if: success() || failure() # always run even if the previous step fails
-        uses: muinmomin/webhook-action@v1.0.0
-        with:
-          url: "https://pulse-7-container.qtestnet.com/webhook/f8525ead-f79b-4afb-8873-b374c421fb5c"
-          # data: "${{ steps.xml2json.outputs.output }}"
-          data: "${{ steps.read_file.outputs.contents }}"
-          #data: 'JSON.stringify("${{ steps.read_file.outputs.contents }}")'
+     #- name: invoke chatops pulse with json
+     #   if: success() || failure() # always run even if the previous step fails
+     #   uses: muinmomin/webhook-action@v1.0.0
+     #   with:
+     #     url: "https://pulse-7-container.qtestnet.com/webhook/f8525ead-f79b-4afb-8873-b374c421fb5c"
+     #     # data: "${{ steps.xml2json.outputs.output }}"
+     #     data: "${{ steps.read_file.outputs.contents }}"
+     #     #data: 'JSON.stringify("${{ steps.read_file.outputs.contents }}")'
