Update HWU.yml

diff --git a/.github/workflows/HWU.yml b/.github/workflows/HWU.yml
--- a/.github/workflows/HWU.yml
+++ b/.github/workflows/HWU.yml
@@ -72,19 +72,19 @@ jobs:
         with: 
           path: "junit-sample/target/surefire-reports/TEST-sample.junit.CalculateTest.xml"
        
-      - name: File contents
-        if: success() || failure() # always run even if the previous step fails
-        run: |                          
-          MULTI_LINES_TEXT="this is line one \n
-                            this is line two \n
-                            this is line three \n"    
-
-          echo "MULTI_LINES_TEXT_ENV_VAR<<EOF" >> $GITHUB_ENV
-          # here we can place the command that will generate multi-line text
-          echo $MULTI_LINES_TEXT >> $GITHUB_ENV
-          echo "EOF" >> $GITHUB_ENV
-          encod_data=`echo -n $GITHUB_ENV | base64`          
-          echo "Encoded text is : $encod_data"
+      #- name: File contents
+      #  if: success() || failure() # always run even if the previous step fails
+      #  run: |                          
+      #    MULTI_LINES_TEXT="this is line one \n
+      #                      this is line two \n
+      #                      this is line three \n"    
+      #
+      #    echo "MULTI_LINES_TEXT_ENV_VAR<<EOF" >> $GITHUB_ENV
+      #    # here we can place the command that will generate multi-line text
+      #    echo $MULTI_LINES_TEXT >> $GITHUB_ENV
+      #    echo "EOF" >> $GITHUB_ENV
+      #    encod_data=`echo -n $GITHUB_ENV | base64`          
+      #    echo "Encoded text is : $encod_data"
           
       - name: Create base64 file
         if: success() || failure() # always run even if the previous step fails
@@ -93,10 +93,10 @@ jobs:
           encod_data=`echo -n $GITHUB_ENV | base64`          
           echo "Encoded text is : $encod_data"
           
-      - name: Using the previously defined environment variable
-        if: success() || failure() # always run even if the previous step fails
-        run: |
-          echo ${{ env.MULTI_LINES_TEXT }}
+      #- name: Using the previously defined environment variable
+      #  if: success() || failure() # always run even if the previous step fails
+      #  run: |
+      #    echo ${{ env.MULTI_LINES_TEXT }}
  
       - name: Parser results
         if: success() || failure() # always run even if the previous step fails
