Update HWU.yml

diff --git a/.github/workflows/HWU.yml b/.github/workflows/HWU.yml
--- a/.github/workflows/HWU.yml
+++ b/.github/workflows/HWU.yml
@@ -15,9 +15,9 @@ jobs:
           cache: maven
       - name: Build and Run tests
         run: mvn test --batch-mode --fail-at-end
-      - name: Publish Test Report
-        if: success() || failure()
-        uses: scacap/action-surefire-report@v1
+    #  - name: Publish Test Report
+    #    if: success() || failure()
+    #    uses: scacap/action-surefire-report@v1
       - name: Fetch action
         if: success() || failure() # always run even if the previous step fails
         id: pl
@@ -41,16 +41,16 @@ jobs:
     #      if test -f "$FILE"; then
     #        echo "$FILE exists."
     #      fi
-      - name: Read package.json
-        if: success() || failure() # always run even if the previous step fails
-        id: package
-        uses: juliangruber/read-file-action@v1.1.6
-        with:
-          path: junit-sample/target/surefire-reports/TEST-sample.junit.CalculateTest.xml
-      - name: Echo package.json
-        if: success() || failure() # always run even if the previous step fails
-        #run: echo "${{ steps.package.outputs.content }}"  
-        run: cat "${ {steps.package.outputs.content }}"  
+    #  - name: Read package.json
+    #    if: success() || failure() # always run even if the previous step fails
+    #    id: package
+    #    uses: juliangruber/read-file-action@v1.1.6
+    #    with:
+    #      path: junit-sample/target/surefire-reports/TEST-sample.junit.CalculateTest.xml
+    #  - name: Echo package.json
+    #    if: success() || failure() # always run even if the previous step fails
+    #    #run: echo "${{ steps.package.outputs.content }}"  
+    #    run: cat "${ {steps.package.outputs.content }}"  
      
      # - name: send via curl
      #   if: success() || failure() # always run even if the previous step fails
@@ -104,25 +104,26 @@ jobs:
         run: |
           echo ${{ env.encod_data }}    
           
-      - name: Parser results
-        if: success() || failure() # always run even if the previous step fails
-        uses: muinmomin/webhook-action@v1.0.0
-        with:
-          url: "https://pulse-7-container.qtestnet.com/webhook/53b32c57-368c-4b9b-a4e0-af11389c5438"
-          data: '{"projectId": "106715" ,"testcycle": "6334424","result": "$env.encod_data"}'
-          #data: '{"projectId": "106715" ,"testcycle": "6334424","result": base64 "junit-sample/target/surefire-reports/TEST-sample.junit.CalculateTest.xml"}'
-          #data: '{"projectId": "106715" ,"testcycle": "6334424","result":"$myJson"}'        
-          #data: '{"projectId": "106715" ,"testcycle": "6334424","result":"${{ steps.read_file.outputs.contents}}"}'         
-         # data: "${{ steps.xml2json.outputs.output }}"     
+   #   - name: Parser results
+   #     if: success() || failure() # always run even if the previous step fails
+   #     uses: muinmomin/webhook-action@v1.0.0
+   #     with:
+   #       url: "https://pulse-7-container.qtestnet.com/webhook/53b32c57-368c-4b9b-a4e0-af11389c5438"
+   #       data: '{"projectId": "106715" ,"testcycle": "6334424","result": "$env.encod_data"}'
+   #       #data: '{"projectId": "106715" ,"testcycle": "6334424","result": base64 "junit-sample/target/surefire-reports/TEST-sample.junit.CalculateTest.xml"}'
+   #       #data: '{"projectId": "106715" ,"testcycle": "6334424","result":"$myJson"}'        
+   #       #data: '{"projectId": "106715" ,"testcycle": "6334424","result":"${{ steps.read_file.outputs.contents}}"}'         
+   #      # data: "${{ steps.xml2json.outputs.output }}"     
          
       - name: send via curl
         if: success() || failure() # always run even if the previous step fails
         #curl --request POST https://pulse-7-container.qtestnet.com/webhook/53b32c57-368c-4b9b-a4e0-af11389c5438 -d "projectId=106715&testcycle=6335148&result=$env.encod_data"
         run: |
            echo ${{ env.encod_data }} 
-           curlComandbase='--request POST https://pulse-7-container.qtestnet.com/webhook/53b32c57-368c-4b9b-a4e0-af11389c5438 -d "projectId=106715&testcycle=6335148&result=${{ env.encod_data }}'
-           echo "$curlComandbase"
-           curl $curlComandbase
+           curlComandbase="--request POST https://pulse-7-container.qtestnet.com/webhook/53b32c57-368c-4b9b-a4e0-af11389c5438 -d"
+           curlComandbase="${curlComandbase} projectId=106715&testcycle=6335148&result=${{ env.encod_data }}"
+           echo "${curlComandbase}"
+           curl ${curlComandbase}
            
       - name: invoke chatops pulse with json
         if: success() || failure() # always run even if the previous step fails
