Update HWU.yml

diff --git a/.github/workflows/HWU.yml b/.github/workflows/HWU.yml
--- a/.github/workflows/HWU.yml
+++ b/.github/workflows/HWU.yml
@@ -67,15 +67,19 @@ jobs:
         uses: andstor/file-reader-action@v1.0.0
         with: 
           path: "junit-sample/target/surefire-reports/TEST-sample.junit.CalculateTest.xml"
-    #  - name: File contents
-    #    if: success() || failure() # always run even if the previous step fails
-    #    run: echo "${ steps.read_file.outputs.contents }"
+      - name: File contents
+        if: success() || failure() # always run even if the previous step fails
+        #run: echo "${ steps.read_file.outputs.contents }"
+        run: const obj = "${ steps.read_file.outputs.contents }"
+             const myJson = JSON.stringify(obj);
+             echo $myJson
       - name: Parser results
         if: success() || failure() # always run even if the previous step fails
         uses: muinmomin/webhook-action@v1.0.0
         with:
           url: "https://pulse-7-container.qtestnet.com/webhook/53b32c57-368c-4b9b-a4e0-af11389c5438"
-          data: '{"projectId": "106715" ,"testcycle": "6334424","result":"${{ steps.read_file.outputs.contents}}"}'         
+          data: '{"projectId": "106715" ,"testcycle": "6334424","result":"$myJson'         
+          #data: '{"projectId": "106715" ,"testcycle": "6334424","result":"${{ steps.read_file.outputs.contents}}"}'         
          # data: "${{ steps.xml2json.outputs.output }}"         
       - name: invoke chatops pulse with json
         if: success() || failure() # always run even if the previous step fails
