Update HWU.yml

diff --git a/.github/workflows/HWU.yml b/.github/workflows/HWU.yml
--- a/.github/workflows/HWU.yml
+++ b/.github/workflows/HWU.yml
@@ -49,10 +49,8 @@ jobs:
           path: junit-sample/target/surefire-reports/TEST-sample.junit.CalculateTest.xml
       - name: Echo package.json
         if: success() || failure() # always run even if the previous step fails
-        #run: echo "${{ steps.package.outputs.content }}"  
-        run: 
-             cat "${{ steps.package.outputs.content }}" 
-   
+        run: echo "${{ steps.package.outputs.content }}"  
+        
       - name: Parser results v1
         if: success() || failure() # always run even if the previous step fails
         uses: muinmomin/webhook-action@v1.0.0
@@ -81,7 +79,13 @@ jobs:
           echo "EOF" >> $GITHUB_ENV
           encod_data=`echo -n $GITHUB_ENV | base64`          
           echo "Encoded text is : $encod_data"
-                 
+          
+      - name: Create base64 file
+        if: success() || failure() # always run even if the previous step fails
+        run: |
+          echo "junit-sample/target/surefire-reports/TEST-sample.junit.CalculateTest.xml" >> $GITHUB_ENV
+          encod_data=`echo -n $GITHUB_ENV | base64`          
+          echo "Encoded text is : $encod_data"
           
       - name: Using the previously defined environment variable
         if: success() || failure() # always run even if the previous step fails
