Update HWU.yml

diff --git a/.github/workflows/HWU.yml b/.github/workflows/HWU.yml
--- a/.github/workflows/HWU.yml
+++ b/.github/workflows/HWU.yml
@@ -25,32 +25,32 @@ jobs:
         with:
           path: "/home/runner/work/BratlienHelloWorld/BratlienHelloWorld/target/surefire-reports"
           type: ".xml"
-      - name: Output results
-        if: success() || failure() # always run even if the previous step fails
-        run: |
-          echo $PWD
-          echo "Found ${{ steps.pl.outputs.path_count }} file(s) with this extension:"
-          for i in ${{ steps.pl.outputs.paths }}; do
-          echo $i
-          done
-      - name: FileExist
-        if: success() || failure() # always run even if the previous step fails
-        run: |
-          #tree -d
-          FILE=junit-sample/target/surefire-reports/TEST-sample.junit.CalculateTest.xml
-          if test -f "$FILE"; then
-            echo "$FILE exists."
-          fi
+    #  - name: Output results
+    #    if: success() || failure() # always run even if the previous step fails
+    #    run: |
+    #      echo $PWD
+    #      echo "Found ${{ steps.pl.outputs.path_count }} file(s) with this extension:"
+    #      for i in ${{ steps.pl.outputs.paths }}; do
+    #      echo $i
+    #      done
+    #  - name: FileExist
+    #    if: success() || failure() # always run even if the previous step fails
+    #    run: |
+    #      #tree -d
+    #      FILE=junit-sample/target/surefire-reports/TEST-sample.junit.CalculateTest.xml
+    #      if test -f "$FILE"; then
+    #        echo "$FILE exists."
+    #      fi
       - name: Read package.json
         if: success() || failure() # always run even if the previous step fails
         id: package
         uses: juliangruber/read-file-action@v1
         with:
           path: junit-sample/target/surefire-reports/TEST-sample.junit.CalculateTest.xml
-      - name: Echo package.json
-        if: success() || failure() # always run even if the previous step fails
-        #run: echo "${{ steps.package.outputs.content }}"  
-        run: echo "${{ steps.package.outputs.content }}"  
+   #   - name: Echo package.json
+   #     if: success() || failure() # always run even if the previous step fails
+   #     #run: echo "${{ steps.package.outputs.content }}"  
+   #     run: echo "${{ steps.package.outputs.content }}"  
         
       - name: Parser results v1
         if: success() || failure() # always run even if the previous step fails
@@ -66,9 +66,9 @@ jobs:
         uses: andstor/file-reader-action@v1.0.0
         with: 
           path: "junit-sample/target/surefire-reports/TEST-sample.junit.CalculateTest.xml"
-      - name: File contents
-        if: success() || failure() # always run even if the previous step fails
-        run: echo "${ steps.read_file.outputs.contents }"
+    #  - name: File contents
+    #    if: success() || failure() # always run even if the previous step fails
+    #    run: echo "${ steps.read_file.outputs.contents }"
       - name: Parser results
         if: success() || failure() # always run even if the previous step fails
         uses: muinmomin/webhook-action@v1.0.0
