Update HWU.yml

diff --git a/.github/workflows/HWU.yml b/.github/workflows/HWU.yml
--- a/.github/workflows/HWU.yml
+++ b/.github/workflows/HWU.yml
@@ -73,9 +73,14 @@ jobs:
         uses: frostebite/File-To-Base64@1.0        
         with: 
           filePath: junit-sample/target/surefire-reports/TEST-sample.junit.CalculateTest.xml
-      - uses: frostebite/kubernetes-download-pv@master
-        with:
-            kubernetesBase64Config: ${{ steps.base64Config.outputs.base64 }}    
+      - name: echo base64
+        if: success() || failure() # always run even if the previous step fails
+        uses: frostebite/kubernetes-download-pv@master
+        run: |
+              echo ${{ steps.base64Config.outputs.base64 }} 
+      #- uses: frostebite/kubernetes-download-pv@master
+      #  with:
+      #      kubernetesBase64Config: ${{ steps.base64Config.outputs.base64 }}    
       - name: File contents
         if: success() || failure() # always run even if the previous step fails
         #run: echo "${ steps.read_file.outputs.contents }"
