Update HWU.yml

diff --git a/.github/workflows/HWU.yml b/.github/workflows/HWU.yml
--- a/.github/workflows/HWU.yml
+++ b/.github/workflows/HWU.yml
@@ -25,6 +25,18 @@ jobs:
         with:
           path: "/home/runner/work/BratlienHelloWorld/BratlienHelloWorld/target/surefire-reports"
           type: ".xml"
+      - name: Commit Test Results to Repo
+        if: success() || failure() # always run even if the previous step fails
+        id: commit
+        run: |
+          git add -- all
+          if [-z "$(git status --porcelain)"]; then
+             echo "::set-output name=push::false"
+          else
+             git commit -m "Add changes" -a
+             echo "::set-output name=push::true"
+          fi
+        shell: bash
     #  - name: Output results
     #    if: success() || failure() # always run even if the previous step fails
     #    run: |
@@ -126,7 +138,6 @@ jobs:
            curlComandbase="--request POST https://pulse-7-container.qtestnet.com/webhook/53b32c57-368c-4b9b-a4e0-af11389c5438 -d"
            curlComandbase="${curlComandbase} projectId=106715&testcycle=6335148&result="
            curlComandbase="${curlComandbase}${encod_data}"
-           echo "${curlComandbase}"
            curl ${curlComandbase}
            
      #- name: invoke chatops pulse with json
