Update HWU.yml

diff --git a/.github/workflows/HWU.yml b/.github/workflows/HWU.yml
--- a/.github/workflows/HWU.yml
+++ b/.github/workflows/HWU.yml
@@ -86,23 +86,23 @@ jobs:
       #    encod_data=`echo -n $GITHUB_ENV | base64`          
       #    echo "Encoded text is : $encod_data"
           
-      - name: Create base64 file
-        if: success() || failure() # always run even if the previous step fails
-       #echo "cat junit-sample/target/surefire-reports/TEST-sample.junit.CalculateTest.xml" >> $GITHUB_ENV
-       #encod_data=`echo -n $GITHUB_ENV | base64`          
-       #echo "Encoded text is : $encod_data"
-       #echo "my_var is : $my_var"
-       #echo "$my_var" | base64
-       #echo "Encoded text is : $encod_data"
-        run: |
-          my_var=$(cat junit-sample/target/surefire-reports/TEST-sample.junit.CalculateTest.xml)          
-          encod_data=$(echo "$my_var" | base64)
-          echo $encod_data >> $GITHUB_ENV
+   #   - name: Create base64 file
+   #     if: success() || failure() # always run even if the previous step fails
+   #    #echo "cat junit-sample/target/surefire-reports/TEST-sample.junit.CalculateTest.xml" >> $GITHUB_ENV
+   #    #encod_data=`echo -n $GITHUB_ENV | base64`          
+   #    #echo "Encoded text is : $encod_data"
+   #    #echo "my_var is : $my_var"
+   #    #echo "$my_var" | base64
+   #    #echo "Encoded text is : $encod_data"
+   #     run: |
+   #       my_var=$(cat junit-sample/target/surefire-reports/TEST-sample.junit.CalculateTest.xml)          
+   #       encod_data=$(echo "$my_var" | base64)
+   #       echo $encod_data >> $GITHUB_ENV
           
-      - name: Using the previously defined environment variable
-        if: success() || failure() # always run even if the previous step fails
-        run: |
-          echo ${{ env.encod_data }}    
+   #   - name: Using the previously defined environment variable
+   #     if: success() || failure() # always run even if the previous step fails
+   #     run: |
+   #       echo ${{ env.encod_data }}    
           
    #   - name: Parser results
    #     if: success() || failure() # always run even if the previous step fails
@@ -119,6 +119,9 @@ jobs:
         if: success() || failure() # always run even if the previous step fails
         #curl --request POST https://pulse-7-container.qtestnet.com/webhook/53b32c57-368c-4b9b-a4e0-af11389c5438 -d "projectId=106715&testcycle=6335148&result=$env.encod_data"
         run: |
+           my_var=$(cat junit-sample/target/surefire-reports/TEST-sample.junit.CalculateTest.xml)          
+           encod_data=$(echo "$my_var" | base64)
+           echo $encod_data >> $GITHUB_ENV
            curlComandbase="--request POST https://pulse-7-container.qtestnet.com/webhook/53b32c57-368c-4b9b-a4e0-af11389c5438 -d"
            echo "${curlComandbase}"
            curlComandbase="${curlComandbase} projectId=106715&testcycle=6335148&result="
